import Report from "../models/Report.js";
import Admin from "../models/Admin.js";
import Job from "../models/Job.js";
import Application from "../models/Application.js";
import Interview from "../models/Interview.js";
import Notification from "../models/Notification.js";
import mongoose from "mongoose";

/**
 * @desc    Generate a report based on live metrics and notify Employer
 * @route   POST /api/reports/generate
 * @access  Private (Admin)
 */
export const generateReport = async (req, res) => {
  try {
    // 1. Verify Admin and their tied Employer
    const admin = await Admin.findById(req.user._id);

    // ✅ Matches your Admin.js model field: 'employerId'
    if (!admin || !admin.employerId) {
      console.warn(`403 Unauthorized: Admin ${req.user._id} missing employerId link.`);
      return res.status(403).json({ 
        message: "Admin not authorized or not tied to an employer account." 
      });
    }

    const linkedEmployerId = admin.employerId;

    // 2. Optimized Parallel Metric Calculation
    const [
      activeJobs, 
      totalApps, 
      shortlistedApps, 
      employerJobIds,
      hireCount
    ] = await Promise.all([
      Job.countDocuments({ employerId: linkedEmployerId, status: "active" }), 
      Application.countDocuments({ employerId: linkedEmployerId }), 
      Application.countDocuments({ employerId: linkedEmployerId, status: "shortlisted" }), 
      Job.find({ employerId: linkedEmployerId }).distinct("_id"), 
      Application.countDocuments({ employerId: linkedEmployerId, status: "hired" }) 
    ]);

    const interviewCount = await Interview.countDocuments({ 
      jobId: { $in: employerJobIds } 
    });

    const metrics = {
      activeListings: activeJobs,
      totalApplications: totalApps,
      shortlisted: shortlistedApps,
      totalInterviews: interviewCount,
      hires: hireCount,
      placementRate: totalApps > 0 ? Math.round((hireCount / totalApps) * 100) : 0
    };

    // 3. Create and Save the Report
    const report = await Report.create({
      employer: linkedEmployerId, // The reference field in the Report model
      admin: admin._id,
      metrics,
      status: "published"
    });

    // 4. Notify the Employer
    await Notification.create({
      userId: linkedEmployerId,
      type: "message", 
      content: `New analytics report: Your hiring data has been synchronized.`,
      link: `/employer/dashboard/reports`
    });

    // 5. Emit Socket Event for real-time Dashboard update
    const io = req.app.get("socketio");
    if (io) {
      io.to(linkedEmployerId.toString()).emit("receive_notification", {
        message: "Your analytics dashboard has been updated.",
        type: "report",
        reportId: report._id
      });
    }

    res.status(201).json({ 
      message: "Report synchronized and employer notified", 
      report 
    });
  } catch (error) {
    console.error("GENERATE REPORT ERROR:", error);
    res.status(500).json({ message: "Error generating report", error: error.message });
  }
};

/**
 * @desc    Get the most recent published report for an Employer
 * @route   GET /api/reports/latest
 * @access  Private (Employer)
 */
export const getEmployerLatestReport = async (req, res) => {
  try {
    // Try to find the ID from either the employerId field or the base _id
    const searchId = req.user.employerId || req.user._id;

    const report = await Report.findOne({ 
      employer: searchId, 
      status: "published" 
    })
    .sort({ createdAt: -1 })
    .populate("admin", "name");

    if (!report) {
      return res.status(404).json({ message: "No analytics reports found for this account." });
    }

    res.json(report);
  } catch (error) {
    res.status(500).json({ message: "Error fetching latest report", error: error.message });
  }
};

/**
 * @desc    Get all reports generated by a specific Admin
 */
export const getReports = async (req, res) => {
  try {
    const reports = await Report.find({ admin: req.user._id })
      .populate("employer", "companyName industry")
      .sort({ createdAt: -1 });

    res.json(reports);
  } catch (error) {
    res.status(500).json({ message: "Error fetching reports", error: error.message });
  }
};

/**
 * @desc    Get single report by ID with access control
 */
export const getReportById = async (req, res) => {
  try {
    const report = await Report.findById(req.params.id)
      .populate("employer", "companyName industry email")
      .populate("admin", "name email");

    if (!report) return res.status(404).json({ message: "Report not found" });

    const userId = req.user._id.toString();
    
    // Check if the user is the Admin who made it OR the Employer it belongs to
    const isAuthorized = 
      report.admin?._id.toString() === userId || 
      report.employer?._id.toString() === userId;

    if (!isAuthorized) {
      return res.status(403).json({ message: "Access denied." });
    }

    res.json(report);
  } catch (error) {
    res.status(500).json({ message: "Error fetching report", error: error.message });
  }
};