import Report from "../models/Report.js";
import Admin from "../models/Admin.js";
import Job from "../models/Job.js";
import Application from "../models/Application.js";
import Interview from "../models/Interview.js";
import Notification from "../models/Notification.js";

// ==========================================
// Generate and save a report (Optimized)
// ==========================================
export const generateReport = async (req, res) => {
  try {
    // 1. Verify Admin and their tied Employer
    const admin = await Admin.findById(req.user._id);

    if (!admin || !admin.employer) {
      return res.status(403).json({ message: "Admin not authorized or not tied to an employer" });
    }

    const employerId = admin.employer;

    // 2. Optimized Metric Calculation 
    // We query the collections directly for accurate counts
    const [jobCount, appCount, interviewCount, hireCount] = await Promise.all([
      Job.countDocuments({ employerId }),
      Application.countDocuments({ employerId }),
      // Interviews usually link to Jobs, so we find interviews for all jobs belonging to this employer
      Interview.countDocuments({ 
        jobId: { $in: await Job.find({ employerId }).distinct("_id") } 
      }),
      Application.countDocuments({ employerId, status: "hired" }) 
    ]);

    const metrics = {
      totalJobs: jobCount,
      totalApplications: appCount,
      totalInterviews: interviewCount,
      hires: hireCount
    };

    // 3. Create and Save the Report
    const report = await Report.create({
      employer: employerId,
      admin: admin._id,
      metrics
    });

    // 4. Notify the Employer that a report is ready
    await Notification.create({
      userId: employerId,
      type: "message", // Ensure "message" is in your Notification model enum
      content: `A new performance report for your company has been generated by the Admin.`,
      link: `/dashboard/reports/${report._id}`
    });

    res.status(201).json({ message: "Report generated and employer notified", report });
  } catch (error) {
    console.error("GENERATE REPORT ERROR:", error);
    res.status(500).json({ message: "Error generating report", error: error.message });
  }
};

// ==========================================
// Get all reports for an admin
// ==========================================
export const getReports = async (req, res) => {
  try {
    // Show reports created by this admin, populated with employer details
    const reports = await Report.find({ admin: req.user._id })
      .populate("employer", "companyName industry")
      .sort({ createdAt: -1 }); // Newest first

    res.json(reports);
  } catch (error) {
    res.status(500).json({ message: "Error fetching reports", error: error.message });
  }
};

// ==========================================
// Get a single report by ID
// ==========================================
export const getReportById = async (req, res) => {
  try {
    const report = await Report.findById(req.params.id)
      .populate("employer", "companyName industry email")
      .populate("admin", "name email");

    if (!report) return res.status(404).json({ message: "Report not found" });

    // Basic Security: Only the Admin who made it or the Employer it belongs to can see it
    const isAuthorized = 
      report.admin._id.toString() === req.user._id.toString() || 
      report.employer._id.toString() === req.user._id.toString();

    if (!isAuthorized) {
      return res.status(403).json({ message: "Access denied to this report" });
    }

    res.json(report);
  } catch (error) {
    res.status(500).json({ message: "Error fetching report", error: error.message });
  }
};