import express from "express";
import { 
  generateReport, 
  getReports, 
  getReportById, 
  getEmployerLatestReport 
} from "../controllers/reportController.js";
// ✅ Removed 'admin' and 'employer' from the import to stop the SyntaxError
import { protect } from "../middleware/authMiddleware.js";

const router = express.Router();

/**
 * @route   GET /api/reports/latest
 * @desc    Fetch the most recent published report for the logged-in Employer
 */
router.get("/latest", protect, getEmployerLatestReport);

/**
 * @route   POST /api/reports/generate
 * @desc    Generate a new report (Admin only - verified inside controller)
 */
router.post("/generate", protect, generateReport);

/**
 * @route   GET /api/reports
 * @desc    Get all reports generated by the logged-in Admin
 */
router.get("/", protect, getReports);

/**
 * @route   GET /api/reports/:id
 * @desc    Get a specific report by ID
 */
router.get("/:id", protect, getReportById);

export default router;